.TH "geds_set_length" "3" "19 марта 2013" "Linux" "GEDS Functions Manual"
.
.SH ИМЯ
geds_set_length - выбрать длину подписи
.
.SH СИНТАКСИС
.nf
.B #include <geds.h>
.sp
.BI "int geds_set_length(geds_context *" ctx " int " len );
.fi
.
.SH ОПИСАНИЕ
Функция \fBgeds_set_length\fP(3) устанавливает длину подписи,
которая будет сгенерирована/проверена.
Параметр \fIlen\fP может принимать 2 возможных значения:
\fBGEDS_LEN_512\fP и \fBGEDS_LEN_1024\fP
для получение подписей длиной 512 и 1024 бита.
.
.SH "ВОЗВРАЩАЕМОЕ ЗНАЧЕНИЕ"
\fBgeds_sel_length\fP(3) возвращает \fBGEDS_OK\fP,
либо \fBGEDS_ERR\fP,
если было передано невалидное значение \fIlen\fP.
.
.SH "СМОТРИ ТАКЖЕ"
.BR geds_generate (3),
.BR geds_verify (3),
.BR geds_set_point (3),
.BR geds_set_curve (3),
.BR geds_set_subgroup (3),
.BR geds_set_rnd (3),
.BR geds_set_signature (3),
.BR geds_get_signature (3)
.BR geds_context_new (3),
.BR geds_context_free (3),
.BR geds_point_new (3),
.BR geds_point_free (3)
