.TH "geds_context_free" "3" "19 марта 2013" "Linux" "GEDS Functions Manual"
.
.SH ИМЯ
geds_context_free - освобождает память
.
.SH СИНТАКСИС
.nf
.B #include <geds.h>
.sp
.BI "void geds_context_free(geds_context **" ctx );
.fi
.
.SH ОПИСАНИЕ
Функция \fBgeds_context_free\fP(3) освобождает память,
выделенную ранее с помощью \fBgeds_context_new\fP(3),
и записывает в *\fIctx\fP значение NULL.
.
.SH "СМОТРИ ТАКЖЕ"
.BR geds_context_new (3),
.BR geds_point_new (3),
.BR geds_poin_free (3),
.BR geds_generate (3),
.BR geds_check (3)
