.TH "geds_point_free" "3" "19 марта 2013" "Linux" "GEDS Functions Manual"
.
.SH ИМЯ
geds_point_free - освобождает память, содержащую точку
.
.SH СИНТАКСИС
.nf
.B #include <geds.h>
.sp
.BI "void geds_point_free(geds_point **" P );
.fi
.
.SH ОПИСАНИЕ
Функция \fBgeds_point_free\fP(3) освобждает память,
выделенную ранее с помощью \fBgeds_point_new\fP(3).
.
.SH "СМОТРИ ТАКЖЕ"
.BR geds_point_new (3),
.BR geds_context_new (3),
.BR geds_context_free (3),
.BR geds_generate (3),
.BR geds_check (3)
